Repository medizininformatik-initiative/feasibility-backend, pull requests merged in 2023-05, with the labels that each got.

#124 Encrypt the Query Result Log
  README.md
  src/main/java/de/numcodex/feasibility_gui_backend/query/result/Decryptor.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/result/EncryptingEncoder.java
  src/main/resources/logback.xml
  src/test/java/de/numcodex/feasibility_gui_backend/query/result/DecryptorTest.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/result/EncryptingEncoderTest.java
  src/test/resources/de/numcodex/feasibility_gui_backend/query/result/result.log
  src/test/resources/logback-test.xml
Labels: enhancement

#131 #127 - Fix code scanning alert - json stack overflow vulnerability
  pom.xml
Labels: security

#130 #128 - Fix code scanning alert - Spring Boot Security Bypass with Wildcard Pattern Matching on Cloud Foundry
  pom.xml
Labels: security

#129 #126 - Fix code scanning alert - Spring Security logout not clearing security context
  pom.xml
Labels: security

#133 Hotfix/v3.1.1
  CHANGELOG.md
  pom.xml
  src/main/resources/application.yml
Labels: bug

#119 #116 - Improve error handling
  src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/api/status/FeasibilityIssue.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/api/status/FeasibilityIssueSerializer.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingErrorAttributes.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/ratelimiting/RateLimitingInterceptor.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/v2/QueryHandlerRestController.java
  src/main/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyService.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/v2/QueryHandlerRestControllerIT.java
Labels: enhancement

#136 #135 - Adapt spring security configuration to newer api
  src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java
Labels: refactoring

#125 #122 - Replace v1 examples in readme
  README.md
Labels: documentation

#140 #139 - Make result log encryption optional
  README.md
  pom.xml
  src/main/resources/logback.xml
Labels: enhancement
