Repository medizininformatik-initiative/feasibility-backend, pull requests merged in 2023-03, with the labels that each got.

#72 Switch to Non Focal Based Docker Image
  Dockerfile
Labels: security

#73 Fix CVE-2023-24057 by Updating HAPI to v6.4.2
  pom.xml
Labels: security, dependencies

#70 #66 - Fix Potential Bug in QueryHandlerService.getAuthorId Able to Return Null
  src/main/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerService.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/QueryNotFoundException.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/v1/QueryHandlerRestController.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/v2/QueryHandlerRestController.java
  src/test/java/de/numcodex/feasibility_gui_backend/query/QueryHandlerServiceIT.java
Labels: bug

#81 #79 - CORS failing
  src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java
Labels: bug

#83 #82 - Security for template and terminology endpoint missing
  src/main/java/de/numcodex/feasibility_gui_backend/config/RateLimitingConfig.java
  src/main/java/de/numcodex/feasibility_gui_backend/config/WebSecurityConfig.java
  src/main/java/de/numcodex/feasibility_gui_backend/query/v2/QueryTemplateHandlerRestController.java
  src/main/java/de/numcodex/feasibility_gui_backend/terminology/TerminologyRestController.java
Labels: bug

#99 #97 - Update SnakeYaml to v2.0 to resolve CVE-2022-1471
  pom.xml
Labels: security, dependencies

#104 #100 - Update Spring Boot to 3.0.5
  pom.xml
Labels: security

#107 #106 - Update readme
  README.md
  docker-compose.yml
  src/main/resources/application.yml
Labels: documentation
